In [13]:
import random
import numpy as np
import matplotlib.pyplot as plt

a=np.zeros((12,12))
for i in range(12-2):
  for j in range(12-2):
    a[i+1][j+1]=random.randint(0,255)
b=np.empty((3,3))
for i in range(3):
  for j in range(3):
    b[i][j]=random.randint(0,1)

output=np.zeros((a.shape[0]-b.shape[0]+1,a.shape[1]-b.shape[1]+1))
for i in range(output.shape[0]):
  for j in range(output.shape[0]):
    sum=0
    for m in range(b.shape[0]):
      for n in range(b.shape[1]):
        sum+=b[m][n]*a[i+m][j+n]
    output[i][j]=sum

print(a)
print(b)
print(output)
  # submatrix = arr[np.ix_([0, 3], [1, 3])]
  # [i-1:i+1][j-1:j+1]


[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  79. 188.  67. 231.  39.  56.  50. 124. 134. 110.   0.]
 [  0. 114. 245. 169. 106. 214. 148. 167.  54.  61. 189.   0.]
 [  0. 131.  80.  45. 247.  44. 255.  41. 194.  39.  62.   0.]
 [  0. 101. 195. 147.  81. 181. 194. 152. 216.   7. 212.   0.]
 [  0. 252. 115.  24.  37. 230. 223. 182.  94. 174.  66.   0.]
 [  0.  56. 204. 131.  52. 239. 152.  65. 233. 253. 120.   0.]
 [  0. 198. 158.  81.  36. 112. 124. 227.   6. 147.  23.   0.]
 [  0. 218. 153. 202. 234. 119. 122.  36.  61. 145. 197.   0.]
 [  0. 233. 165. 151. 140.   6. 236. 167. 249. 170. 170.   0.]
 [  0.  74.  23. 141. 215.  57.  56. 139.  75.   9.  31.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
[[1. 0. 0.]
 [1. 1. 1.]
 [0. 1. 1.]]
[[ 626.  748.  761.  657.  688.  460.  451.  423.  618.  433.]
 [ 570.  732. 1000.  847.  998.  864.  660.  565.  529.  446.]
 [ 507.  712.  845.  767. 1027.  900. 1006.  664.  568.  374.]
 [ 663.  713.  56

Mean Filter

In [14]:
c=np.zeros((10,10))
for i in range(output.shape[0]):
  for j in range(output.shape[1]):
    sum=0
    for m in range(b.shape[0]):
      for n in range(b.shape[1]):
        sum+=b[m][n]*a[i+m][j+n]
    c[i][j]=sum/9

print(c)

[[ 69.55555556  83.11111111  84.55555556  73.          76.44444444
   51.11111111  50.11111111  47.          68.66666667  48.11111111]
 [ 63.33333333  81.33333333 111.11111111  94.11111111 110.88888889
   96.          73.33333333  62.77777778  58.77777778  49.55555556]
 [ 56.33333333  79.11111111  93.88888889  85.22222222 114.11111111
  100.         111.77777778  73.77777778  63.11111111  41.55555556]
 [ 73.66666667  79.22222222  62.66666667  80.11111111 128.44444444
  108.44444444 121.44444444  76.          96.55555556  36.        ]
 [ 69.66666667  91.88888889  61.55555556  81.         106.88888889
  114.77777778 110.11111111 120.88888889 102.55555556  40.77777778]
 [ 68.44444444  98.          68.77777778  66.          79.55555556
  115.22222222 100.66666667  98.44444444  96.66666667  63.33333333]
 [ 80.77777778  94.22222222 101.66666667  79.22222222  62.77777778
   95.55555556  67.33333333  72.33333333  83.44444444  68.88888889]
 [ 85.44444444 120.77777778 115.33333333  86.88888889  

Median Filter

In [15]:
d=np.zeros((10,10))
array=[]
for i in range(output.shape[0]):
  for j in range(output.shape[1]):
    for m in range(b.shape[0]):
      for n in range(b.shape[1]):
        array.append(b[m][n]*a[i+m][j+n])
    array.sort()
    d[i][j]=array[len(array)//2]
    array.clear()

print(d)

[[  0.  67.  67.  39.  39.  39.  50.  50.  61.   0.]
 [  0.  79. 106.  67. 106.  41.  54.  50.  54.   0.]
 [  0.  80.  80.  45. 106.  44. 148.  39.  39.   0.]
 [  0. 101.  37.  45. 181. 152. 152.  41.  66.   0.]
 [  0. 101.  37.  37.  81. 152.  94. 152.  94.   0.]
 [  0.  81.  52.  36.  52. 124.  65.  65.  94.   0.]
 [  0.  81.  81.  81.  52. 112.  36.  61.  23.   0.]
 [  0. 153. 151.  81.  36. 112.  61.  61.  61.   0.]
 [  0. 141. 141.  57.  56.  56. 122.  36.  31.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
